---
user: wheelodex

dbname: wheelodex
dbuser: wheelodex
#dbpass:  # required; no default

venv_path: "/home/{{user}}/virtualenv"
config_file: "/home/{{user}}/config.py"
wsgi_file: "/home/{{user}}/wsgi.py"

wheelodex_log_path: "/home/{{user}}/logs"

upgrade_pip: false
purge_venv: false

#wheel_src:  # required; no default
extras: '[postgres]'

config_options: {}

#errmail_from_addr:  # required; no default
#errmail_to_addr:  # required; no default
#mailgun_smtp_username:  # required; no default
#mailgun_smtp_password:  # required; no default

register_wheels_per_day: 3
register_wheels_start: 0

process_wheels_per_day: 1
process_wheels_start: 6

dbdump_path: /var/backups/wheelodex/postgres
